### ISSUE TITLE
special command fails without cmd_param

### ISSUE THREAD

**Issue by mc-roben** [belohoub/stm32flash#1]
Many thanks for implementing special command feature to stm32flash.

Cannot use special command with only cmd_opcode. Then cmd_param is empty (= NULL) and the program aborts. 

I attached a patch to fix this issue: [stm32flash_0.6-30.patch.txt](https://github.com/belohoub/stm32flash/files/7870851/stm32flash_0.6-30.patch.txt).

**Comment by belohoub** [comment]
Thank you for reporting! 

And actually great timing! My colleague reported two issues internally on Wednesday including this one. I planned to fix this today ;-)

The special command feature is still poorly tested - feel free to report anything!
